##Swagger

#下载所需要的镜像
docker pull swaggerapi/swagger-ui:v3.19.2
docker pull swaggerapi/swagger-editor:v3.6.11

#运行 swagger-ui
docker run -p 8801:8080 -d --name swagger-ui-3.19.2 swaggerapi/swagger-ui:v3.19.2

#For latest, and post v3.0.5 tags, you can specify the default swagger-ui to load in the UI
docker run -p 8080:8080 -e API_URL=http://generator.swagger.io/api/swagger.json swaggerapi/swagger-ui:v3.19.2

#运行 swagger-editor
docker run -d -p 8802:8080 -d --name swagger-editor-3.6.11 swaggerapi/swagger-editor:v3.6.11

#访问http://IP:8080